version: '3'

services:
  spa:
    build:
      context: .
    environment:
      API_HOST: api
      API_PORT: 8080
    ports:
      - '80:80'
    expose:
      - '80'
    depends_on:
      - api
    networks:
      - todo
  api:
    image: pactfoundation/pact-stub-server
    volumes:
      - ./pacts/:/app/pacts
    command: -p 8080 -d pacts
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - todo

networks:
  todo:
